In [196]:
import numpy as np

In [197]:
arr1 = np.array([1,3,5])
print(arr1)

[1 3 5]


In [198]:
arr2 = np.array([[9.2,8.0,7.0],[6.0,5.0,4.0]])
print(arr2)

[[9.2 8.  7. ]
 [6.  5.  4. ]]


In [199]:
# Get Dimensions
print(arr1.ndim)
print(arr2.ndim) 

1
2


In [200]:
# Get Shape
print(arr1.shape)
print(arr2.shape) 

(3,)
(2, 3)


In [201]:
# Get Type
print(arr1.dtype)
# Specify the datatype
arr3 = np.array([1,3,5], dtype='int16')
print(arr3.dtype)

int64
int16


In [202]:
# Get Item Size (in bytes)
print(arr3.itemsize)
print(arr1.itemsize)

2
8


In [203]:
# Get Total Size (in bytes)
print(arr1.nbytes)
print(arr3.nbytes)


24
6


In [204]:
# Operations
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [205]:
# Get a specific element [row,column]
print(a[1,5])
print(a[1,-2]) ## 14 is at -1 and 13 is at -2

13
13


In [206]:
# Get a specific row
a[0,:] # or directly a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [207]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [208]:
# Indexing: [startindex:endindex:stepsize]
a[0,1:6:2] #Start from index 0,1 go up to index 6 increasing by 2
# Note: it doesn't go to the next row

array([2, 4, 6])

In [209]:
# Modifying
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [210]:
a[:,2] = 5 
print(a)
a[:,3] = [1,6]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  1  5  6  7]
 [ 8  9  5  6 12 20 14]]


In [211]:
# 3-d 
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [212]:
# Get a a specific element (outside to inside)
print(b[0,1,1])
print(b[:,0,0])

4
[1 5]


In [213]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [214]:
# Initializing Different Type of Arrays


In [215]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [216]:
# All 1s matrix
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [217]:
# Any other number
np.full((2,3,4), 99, dtype = 'float32')

array([[[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]],

       [[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]]], dtype=float32)

In [218]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(np.full_like(a,4))
print(np.full(a.shape,4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [219]:
# Random decimal numbers (between 0-1)
np.random.rand(4,2,3)

array([[[0.74970341, 0.50538457, 0.53736841],
        [0.87577424, 0.82723109, 0.39813876]],

       [[0.95024192, 0.94786091, 0.47726159],
        [0.64529985, 0.10486631, 0.87024124]],

       [[0.68523762, 0.42644802, 0.80955216],
        [0.14529897, 0.46386749, 0.03918937]],

       [[0.62560102, 0.4223924 , 0.27887327],
        [0.65120617, 0.36962442, 0.17257044]]])

In [220]:
# Random Integer Values 
print(np.random.randint(7, size=(3,3)))  #(0-7, 7 excluded)
print(np.random.randint( 4,7 ,size=(3,3))) #4-7, 7 excluded 

[[6 3 4]
 [2 1 2]
 [2 4 0]]
[[4 4 4]
 [6 4 4]
 [4 5 4]]


In [221]:
# Identity matrix
id1= np.identity(3)
id2 = np.eye(3)
print(id1)
print(id2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [222]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [223]:
# linspace and arange
x = np.arange(0,100,10)  # start, end, step (doesn't include end)
print(x)

y = np.linspace(10,100,10) # start, end, number (slices the size by number, includes end)
print(y)

[ 0 10 20 30 40 50 60 70 80 90]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [224]:
# Reverting a matrix: flip  !!! Reverting the order of rows/columns row1,row2 -> row2,row1
matrix = np.array([[1,2], [3,4]])
rows_order_reversed = np.flip(matrix, axis=0)  # equivalently matrix[::-1,:]
cols_order_reversed = np.flip(matrix, axis=1)  # equivalently matrix[:,::-1]
fully_reversed = np.flip(matrix)  # equivalently matrix[::-1,::-1]

print("rows reversed:\n", rows_order_reversed)
print("columns reversed:\n", cols_order_reversed)
print("fully reversed:\n", fully_reversed)

rows reversed:
 [[3 4]
 [1 2]]
columns reversed:
 [[2 1]
 [4 3]]
fully reversed:
 [[4 3]
 [2 1]]


In [225]:
## Changing the shape of a matrix
matrix = np.array([[1,2], [3,4]])

# reshape: Change the shape of a matrix
matrix_reshaped = np.reshape(matrix, (4,1))
print(matrix_reshaped)
# flatten: Turns the matrix into 1d copy

matrix_flattenned = matrix.flatten()
print(matrix_flattenned)

# ravel: Return a contiguous flattened array.
matrix_ravel = matrix.ravel()
print(matrix_ravel)

# T: Returns the transpose of the m atrix
matrix_transpose = matrix.T
print(matrix_transpose)

# expand_dims: Adds dimensions 
matrix_expanded1 = np.expand_dims(matrix,axis=0) 
matrix_expanded2 = np.expand_dims(matrix,axis=1) 
print(matrix_expanded1)
print(matrix_expanded2)
print(matrix_expanded1.shape)
print(matrix_expanded2.shape)

# squeeze: Remove dimensions of size 1
to_squeeze = np.array([[1], [2]])
squeezed = np.squeeze(to_squeeze,axis=1) # can not select axis 0 since its size is 2
print(to_squeeze.shape)
print(squeezed.shape)


[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[1 2 3 4]
[[1 3]
 [2 4]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
(1, 2, 2)
(2, 1, 2)
(2, 1)
(2,)


In [226]:
# Copying arrays
a = np.array([1,2,3])
b=a # alias, reference
b[0] = 100
print(a,b)

x = np.array([1,2,3])
c = x.copy()   # safe copy
c[0] = 100
print(x,c)

[100   2   3] [100   2   3]
[1 2 3] [100   2   3]


In [227]:
## Math operations
a = np.array([1,2,3,4])

print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)


print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.abs(a))
print(np.round(a))

print(np.sin(a))  # all wrt pi, 3.14.. So sin(1) -> sin((1/3.14) *pi)
print(np.cos(a))
print(np.tan(a))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[1 2 3 4]
[1 2 3 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [228]:
## Boolean masking
a = np.arange(1,11)
print(a)
print(a>5)
print(a[a>5])
print(a[(a>5)&(a<8)])
print(a[(a==3 ) | (a== 7)])

#Note: use &, |, - instead of and, or, not ; (and, or, not) -> incorrect syntax

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
[3 7]


In [229]:
## Aggregate/Statistics
a = np.arange(1,10)
print(a)
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a)) #variance: measures how far each number is spread out from the average (mean)
print(np.min(a))
print(np.max(a))
print(np.argmin(a)) # returns the index of min element
print(np.argmax(a))
print(np.percentile(a, 25)) #returns the element at %25 of the array (0-100 included) !! Uses the sorted array, not by actual indices
print(np.quantile(a, 0.25)) # same but uses 0-1

# With 2d arrays
b = np.array([[1,2,3],[4,5,6]])
print(np.sum(b, axis= 0)) # Sum of columns (go down rows)
print(np.sum(b,axis=1))   # Sum of rows  (go accros columns)

[1 2 3 4 5 6 7 8 9]
45
5.0
5.0
2.581988897471611
6.666666666666667
1
9
0
8
3.0
3.0
[5 7 9]
[ 6 15]


In [230]:
# Sorting and unique values
a = np.array([5,6,8,1,3,5])
print(a)
print(np.sort(a))
print(np.argsort(a)) # Returns the indices that would sort an array in ascending order
print(np.unique(a))
print(np.unique(a,return_counts=True))

[5 6 8 1 3 5]
[1 3 5 5 6 8]
[3 4 5 0 1 2]
[1 3 5 6 8]
(array([1, 3, 5, 6, 8]), array([1, 1, 2, 1, 1]))


In [231]:
# Combinin arrays
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate([a,b]))  # Concatenate along the existing axis (1d array)
print(np.vstack([a,b]))       # Stack arrays vertically (2d array)
print(np.hstack([a,b]))       # Stack arrays horizontally (1d array)
print(np.stack([a,b]))        # Stack arrays along a new axis (2d array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [232]:
# Splitting arrays
a = np.array([1,2,3,99,99,3,2,1])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.split(a,2)) # Split into 2 equal arrays
print(np.split(a,[3,5])) # Split at indices 3 and 5
print(np.vsplit(b,2))    # Split vertically into 2 arrays
print(np.hsplit(b,3))    # Split horizontally into 3 arrays


[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]
[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [233]:
# Finding values
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.where(a == 5))  # Find indices where value equals 5
print(np.where(a > 5))   # Find indices where value is greater than 5
print(np.where(a>5, "high", "low"))  # Returns an array of same shape with "high" or "low" based on condition
print(np.nonzero(a)) # Find indices of non-zero elements

(array([5]),)
(array([6, 7, 8, 9]),)
['low' 'low' 'low' 'low' 'low' 'low' 'high' 'high' 'high' 'high']
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [234]:
# Random numbers
rng = np.random.default_rng(42)  # Create a random number generator
a= np.array([1,2,3,4,5,6,7,8,9,10])  # Example array to shuffle
print(rng.integers(0, 10, size=(3, 3)))  # Generate a 3x3 array of random integers between 0 and 10
print(rng.random((3, 3)))  # Generate a 3x3 array of random floats between 0 and 1
print(rng.choice([1, 2, 3, 4, 5], size=(3, 3)))  # Generate a 3x3 array of random choices from the given list
print(rng.normal(size=(3, 3)))  # Generate a 3x3 array of random numbers from a normal distribution
rng.shuffle(a)  # Shuffle the array in-place
print(a)

[[0 7 6]
 [4 4 8]
 [0 6 2]]
[[0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802]
 [0.92676499 0.64386512 0.82276161]]
[[1 3 3]
 [3 2 1]
 [3 5 1]]
[[ 0.8784503  -0.04992591 -0.18486236]
 [-0.68092954  1.22254134 -0.15452948]
 [-0.42832782 -0.35213355  0.53230919]]
[ 9  2  6  8  5  7  4  3  1 10]


In [235]:
# Linear algebra
a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

# Multiplication
##print(a*b)# doesn't work, it multiplies element by element, they should be broadcastable
print(np.matmul(a,b)) # Regular matrix multiplication, applies rules
print(a @ b)  #same as matmul

# Determinant
c = np.identity(3)
print(np.linalg.det(c))

# Transpose 
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print(m.T)  # rows become columns, columns become rows

# Inverse matrix
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.inv(A))  # inverse of matrix A


# Solving linear equations

# 2x + y = 8
# x + 3y = 13

coefficients = np.array([[2, 1],
                         [1, 3]])

answers = np.array([8, 13])

solution = np.linalg.solve(coefficients, answers)

print(solution)  # [x, y]


# Norm / length of a vector
v = np.array([3, 4])

print(np.linalg.norm(v))  # sqrt(3^2 + 4^2) = 5


# Matrix rank
A = np.array([[1, 2],
              [2, 4]])

print(np.linalg.matrix_rank(A)) # number of indepented rows/columns

# Trace
A = np.array([[1, 2],
              [3, 4]])

print(np.trace(A))  # sum of diagonal elements: 1 + 4 = 5


# Diagonal
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.diag(A))  # gets diagonal values: [1,5,9]


# Eigenvalues and eigenvectors

A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print(values)   # eigenvalues
print(vectors)  # eigenvectors


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]
1.0
[[1 4]
 [2 5]
 [3 6]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[2.2 3.6]
5.0
1
5
[1 5 9]
[2. 3.]
[[1. 0.]
 [0. 1.]]
