In [1]:
import numpy as np

In [ ]:
arr1 = np.array([1,3,5])
print(arr1)

[1 3 5]


In [ ]:
arr2 = np.array([[9.2,8.0,7.0],[6.0,5.0,4.0]])
print(arr2)

[[9.2 8.  7. ]
 [6.  5.  4. ]]


In [ ]:
# Get Dimensions
print(arr1.ndim)
print(arr2.ndim) 

1
2


In [8]:
# Get Shape
print(arr1.shape)
print(arr2.shape) 

(3,)
(2, 3)


In [12]:
# Get Type
print(arr1.dtype)
# Specify the datatype
arr3 = np.array([1,3,5], dtype='int16')
print(arr3.dtype)

int64
int16


In [ ]:
# Get Item Size (in bytes)
print(arr3.itemsize)
print(arr1.itemsize)

2
8


In [15]:
# Get Total Size (in bytes)
print(arr1.nbytes)
print(arr3.nbytes)


24
6


In [ ]:
# Operations
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [row,column]
print(a[1,5])
print(a[1,-2]) ## 14 is at -1 and 13 is at -2

13
13


In [ ]:
# Get a specific row
a[0,:] # or directly a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Indexing: [startindex:endindex:stepsize]
a[0,1:6:2] #Start from index 0,1 go up to index 6 increasing by 2
# Note: it doesn't go to the next row

array([2, 4, 6])

In [34]:
# Modifying
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [37]:
a[:,2] = 5 
print(a)
a[:,3] = [1,6]
print(a)

[[ 1  2  5  1  5  6  7]
 [ 8  9  5  6 12 20 14]]
[[ 1  2  5  1  5  6  7]
 [ 8  9  5  6 12 20 14]]


In [39]:
# 3-d 
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get a a specific element (outside to inside)
print(b[0,1,1])
print(b[:,0,0])

4
[1 5]


In [45]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [46]:
# Initializing Different Type of Arrays


In [48]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
# All 1s matrix
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [53]:
# Any other number
np.full((2,3,4), 99, dtype = 'float32')

array([[[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]],

       [[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]]], dtype=float32)

In [57]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(np.full_like(a,4))
print(np.full(a.shape,4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [62]:
# Random decimal numbers (between 0-1)
np.random.rand(4,2,3)

array([[[0.90696469, 0.71360732, 0.87613384],
        [0.0348701 , 0.08476428, 0.49877299]],

       [[0.85473439, 0.66651507, 0.3896013 ],
        [0.56392238, 0.92925346, 0.59886481]],

       [[0.61444888, 0.53647884, 0.16481312],
        [0.48440505, 0.71498686, 0.41028832]],

       [[0.65683392, 0.34301534, 0.1905971 ],
        [0.72818864, 0.90333815, 0.80815531]]])

In [ ]:
# Random Integer Values 
print(np.random.randint(7, size=(3,3)))  #(0-7, 7 excluded)
print(np.random.randint( 4,7 ,size=(3,3))) #4-7, 7 excluded 

[[0 1 3]
 [5 1 1]
 [3 6 5]]
[[5 4 4]
 [4 5 5]
 [6 6 6]]


In [71]:
# Identity matrix

In [72]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
